Added GNU dircolors to make gls even better. Also found a better Chromium update script, thanks to @cowboy.

diff --git a/bin/chromium_updater b/bin/chromium_updater
--- a/bin/chromium_updater
+++ b/bin/chromium_updater
@@ -1,57 +1,111 @@
 #!/bin/bash
-#
-# Snatched from https://github.com/burntime/Chromium-Nightly-Updater
-#
-# This shell script finds the id of the latest Chromium build,
-# then checks to see if Chromium is running. If it is, the
-# script asks if you want to kill the instance. If you type
-# 'y', then the script kills the process, curls the latest
-# Chromium, then unzips, removes the existing version, 
-# moves the new version to /Applications/, then destroys
-# the temporary files.
-#
-# Should work like magic.
 
-LATEST=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac/LAST_CHANGE`
-CURRENT=`defaults read /Applications/Chromium.app/Contents/Info SVNRevision 2>/dev/null`
-PROCESSID=`ps ux | awk '/Chromium/ && !/awk/ {print $2}'`
+if [[ "$1" == "-h" || "$1" == "--help" ]]; then cat <<HELP
+Chromium Updater
+http://benalman.com/
 
-if [[ $LATEST -eq $CURRENT ]]; then
-  echo "You're already up to date ($LATEST)"
-  exit 0
-fi
-if [ "${PROCESSID[0]}" ];  then
-  echo "Kill current instance of Chromium.app [y/n]"
-  read -n 1 -s confirmation
-fi
-if [ "$confirmation" = "y" ];  then
-  for x in $PROCESSID; do
-    kill -9 $x
-  done
+Usage: $(basename "$0") [revision]
+
+Download and install the latest Chromium and dev tools, modifying the binary
+to use those custom dev tools (downloaded into ~/.dotfiles/caches/chromium).
+See ~.dotfiles/conf/update_chromium_etc.sh for sample dev tools customization.
+
+If a revision isn't specified, the latest stable revision will be installed.
+
+Copyright (c) 2011 "Cowboy" Ben Alman
+Licensed under the MIT license.
+http://benalman.com/about/license/
+HELP
+exit; fi
+
+if [[ "$OSTYPE" =~ ^darwin ]]; then
+  os="Mac"
+  app_file="chrome-mac.zip"
+  app_path="/Applications"
 else
-  if [ $confirmation ]; then
-    echo "Please close Chromium.app and restart the script"
-    exit 0
+  echo "Linux unsupported (for now)."
+  exit 1
+fi
+
+url_base="http://commondatastorage.googleapis.com/chromium-browser-continuous/$os"
+dev_file="devtools_frontend.zip"
+
+dev_path=~/.dotfiles/caches/chromium
+current_revision=$(cat "$dev_path/REVISION" 2>/dev/null)
+
+revision=$1
+
+if [[ ! "$revision" ]]; then
+  echo -n "Checking latest Chromium version..."
+  revision=$(curl -s "$url_base/LAST_CHANGE")
+  if [[ "$revision" =~ ^[0-9]+$ ]]; then
+    echo "OK"
+  else
+    echo "ERROR"
+    echo "Error loading revision data from $url_base/LAST_CHANGE, aborting update."
+    exit 1
   fi
 fi
 
-echo "Getting the latest version ($LATEST)"
-curl -L "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac/$LATEST/chrome-mac.zip" -o /tmp/chrome-mac.zip
-wait
+echo "Attempting to update Chromium to revision $revision."
 
-echo "Unzipping"
-unzip -o -qq /tmp/chrome-mac.zip -d /tmp
-wait
+if [[ "$revision" == "$current_revision" ]]; then
+  if [[ "$1" ]]; then
+    echo "Revision $revision is already installed!"
+  else
+    echo "Already up-to-date!"
+  fi
+  exit
+fi
 
-echo "Remove existing version"
-rm -Rf /Applications/Chromium.app
-wait
+echo
 
-echo "Moving new version"
-cp -R /tmp/chrome-mac/Chromium.app /Applications
-wait
+tmp="$(mktemp -d /tmp/chromiumer.XXXXX)"
+for f in "$app_file" "$dev_file"; do
+  echo "Downloading $f."
+  curl -fLo "$tmp/$f" --progress-bar "$url_base/$revision/$f"
+  if [[ ! -f "$tmp/$f" ]]; then
+    echo "Error downloading $f, aborting update."
+    rm -rf "$tmp"
+    exit 1
+  fi
+done
 
-echo "Cleaning up"
-rm -rf /tmp/chrome-*
-echo "Done"
-exit 0
+echo -en "\nDeleting existing files..."
+rm -rf "$app_path/Chromium.app" "$dev_path"
+echo "OK"
+
+echo -n "Creating new files..."
+mkdir -p "$dev_path"
+devtools_path="$dev_path/devtools"
+echo "$revision" > "$dev_path/REVISION"
+unzip -qo "$tmp/$dev_file" -d "$devtools_path"
+unzip -qo "$tmp/$app_file" -d "$tmp"
+echo "OK"
+
+mv "$tmp/${app_file%.zip}/Chromium.app" "$app_path/"
+
+echo -n "Modifying Chromium bin file to use --debug-devtools-frontend..."
+bin_path="$app_path/Chromium.app/Contents/MacOS"
+bin_file="$bin_path/Chromium"
+mv "$bin_file" "$bin_path/Chromium-bin"
+
+cat > "$bin_file" <<'BASH'
+#!/bin/bash
+devtools=~/.dotfiles/caches/chromium/devtools
+"$0-bin" --debug-devtools-frontend="$devtools"
+BASH
+chmod +x "$bin_file"
+echo "OK"
+
+echo -n "Cleaning up..."
+rm -rf "$tmp"
+echo "OK"
+
+additional=~/.dotfiles/conf/update_chromium_etc.sh
+if [[ -f "$additional" ]]; then
+  echo -e "\nRunning update_chromium_etc.sh..."
+  source "$additional"
+fi
+
+echo -e "\nAll done!"
