Updated getlyrics and added notes.

diff --git a/bin/getlyrics b/bin/getlyrics
--- a/bin/getlyrics
+++ b/bin/getlyrics
@@ -20,7 +20,17 @@
 #		**	gem install cloudapp_api		
 #
 #
-# 	TODO: WRITE REGEX to strip out (FEAT. ARTIST XYZ) - these songs break almost everytime.
+# 	TODO: WRITE REGEX to strip out (FEAT. ARTIST XYZ) - these songs break almost every time.
+#			
+#				# Haven't tested this, but this regex string should/might work:
+#				echo "$song_title" | grep -q "/(.feat.*)/g"
+#				if [ $? -eq 0 ]; then
+#				    STRIP OUT (feat.) and pass the purified string to $artist
+#				else
+#				    proceed as usual if no (feat.) found
+#				fi			
+#	
+#	TODO: Ask (nicely!) for assistance from @febuiles to improve results for artists without singular names (e.g. Marina & the Diamonds fails, by Lyrics Wikia has every albums/song lyric).
 # 	TODO: WRITE REGEX to match 'Sorry, We don'\''t have lyrics for this song yet.' then do or don't do stuff
 # 	TODO: WRITE REGEX to match '{{instrumental}}' then do or don't do stuff
 # 	TODO: WRITE REGEX to account for the variety of different characters w/symbols so lyric-finding is more accurate
@@ -41,16 +51,16 @@ cache_dir=~/.dotfiles/caches/lyrics
 # Let's intro with some ASCII, because why the hell not?
 gltitle="
 /////////////////////////////////////////////////////////////////////////////
-	
-	   _____      _   _                _          
-	  / ____|    | | | |              (_)         
-	 | |  __  ___| |_| |    _   _ _ __ _  ___ ___ 
+			*		*						  
+	*  _____      _   _     *          _          *
+	  / ____|    | | | |              (_)     * 		
+	 | |  __  ___| |_| |    _   _ _ __ _  ___ ___ 	   *
 	 | | |_ |/ _ | __| |   | | | | '__| |/ __/ __|
-	 | |__| |  __| |_| |___| |_| | |  | | (__\__ \\
-	  \_____|\___|\__|______\__, |_|  |_|\___|___/
-	                         __/ |                
-	                        |___/                 
-
+	 | |__| |  __| |_| |___| |_| | |  | | (__\__ \\	  *  *
+	  \_____|\___|\__|______\__, |_|  |_|\___|___/	
+	           *             __/ |  *            	*  
+	*             *         |___/     *      	*      
+			*			*					
 /////////////////////////////////////////////////////////////////////////////	
 "
 echo "$gltitle"
